batch_size: 1
iters: 589533   # 24 epochs

model:
  type: FUTR3D
  use_grid_mask: True
  use_LiDAR: False
  use_Radar: False
  use_Cam: True
  backbone:
    type: ResNet
    style: 'caffe'
    layers: 101
    return_idx: [0, 1, 2, 3]
    dcn_v2: True
    stage_with_dcn: [False, False, True, True]
    output_stride: None
    frozen_stages: 1
    frozen_norm: True
    preprocess: False
  neck:
    type: FPN
    in_channels: [256, 512, 1024, 2048]
    out_channels: 256
    start_level: 1
    add_extra_convs: 'on_output'
    num_outs: 4
    relu_before_extra_convs: True
  head:
    type: DeformableFUTR3DHead
    num_query: 600
    num_classes: 10
    in_channels: 256
    embed_dims: 256
    with_box_refine: True
    as_two_stage: False
    code_size: 10
    code_weights: [1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 0.2, 0.2]
    num_cls_fcs: 2
    num_reg_fcs: 2
    pc_range: [-51.2, -51.2, -5.0, 51.2, 51.2, 3.0]
    transformer:
      type: FUTR3DTransformer
      transformer_decoder:
        type: FUTR3DTransformerDecoder
        num_layers: 6
        return_intermediate: True
        embed_dims: 256
        num_heads: 8
        dropout: 0.1
        attn_dropout: 0.1
        use_LiDAR: False
        use_Cam: True
        use_Radar: False
        num_levels: 4
        num_cams: 6
        radar_dims: 64
        radar_topk: 30
        im2col_step: 64
        use_dconv: True
        feedforward_channels: 512
        feedforward_dropout: 0.1
        normalize_before: False
        pc_range: [-51.2, -51.2, -5.0, 51.2, 51.2, 3.0]
    bbox_coder:
      type: NMSFreeCoder
      post_center_range: [-61.2, -61.2, -10.0, 61.2, 61.2, 10.0]
      pc_range: [-51.2, -51.2, -5.0, 51.2, 51.2, 3.0]
      max_num: 300
      voxel_size: [0.1, 0.1, 0.2]
      num_classes: 10
    assigner:
      type: HungarianAssigner3D
      cls_cost:
        type: FocalLossCost
        weight: 2.0
      reg_cost:
        type: BBox3DL1Cost
        weight: 0.25
      iou_cost:
        type: IoUCost
        weight: 0.0
      pc_range: [-51.2, -51.2, -5.0, 51.2, 51.2, 3.0]
    sampler:
      type: PseudoSampler
    loss_cls:
      type: FocalLoss2D
      gamma: 2.0
      alpha: 0.25
      loss_weight: 2.0
    loss_bbox:
      type: L1Loss
      loss_weight: 0.25



train_dataset:
  type: NuscenesModlityDataset
  dataset_root: ./data/nuscenes
  anno_file: ./data/nuscenes/nuscenes_infos_train.pkl
  transforms:
    # img transforms
    - type: LoadMultiViewImageFromFiles
      to_float32: True
    - type: NormalizeMultiviewImage
      mean: [103.530, 116.280, 123.675]
      std: [1.0, 1.0, 1.0]
    - type: PadMultiViewImage
      size_divisor: 32
    # object
    - type: ObjectRangeFilter
      point_cloud_range: [-51.2, -51.2, -5.0, 51.2, 51.2, 3.0]
      bbox_instance: LiDARInstance3DBoxes
      with_gravity_center: True
    - type: Collect3D
      key: ['img']


val_dataset:
  type: NuscenesModlityDataset
  dataset_root: ./data/nuscenes
  anno_file: ./data/nuscenes/nuscenes_infos_val.pkl
  transforms:
    # img transforms
    - type: LoadMultiViewImageFromFiles
      to_float32: True
    - type: NormalizeMultiviewImage
      mean: [103.530, 116.280, 123.675]
      std: [1.0, 1.0, 1.0]
    - type: PadMultiViewImage
      size_divisor: 32
    - type: Collect3D
      key: ['img']

lr_scheduler:
  type: LinearWarmupMultiStepDecay
  learning_rate: 0.0002
  warmup_steps: 500
  warmup_ratio: 0.000001
  step: [589033, 645179] # 21 23 epoch

optimizer:
  type: AdamW
  weight_decay: 0.01